[package]
name = "gbcemu"
version = "0.1.0"
authors = ["16meyrat <louis.meyrat@mines-paristech.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.4.1"
sdl2 = "0.32"
arrayvec = "0.5"
